cloud:
  aws:
    credentials:
      accessKey: AKIATEK5MYJLYMKKMH4J
      secretKey: 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
    s3:
      bucket: mytube-sns
    region:
      static: ap-northeast-2
    stack:
      auto: false